### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jeanlucaslima** [ideo/shape#1259]
Thanks for opening it up, really. 

I feel sad the project is ending (I really think there were nice things to explore here), but I'm happy IDEO is opening up the source code. 

I just don't see much of a License, since people can spin up their own version, can someone monetize it? What are the limits? If it had an open source license it would be simpler to understand what can and cannot be done.

**Comment by kaptron** [comment]
Hi @jeanlucaslima, thanks for the note, and for the good question. We have added the MIT license, so it's free to use as you wish.
